name: Task
description: Define actionable development work items.
labels: ["task"]
title: "Task: "
assignees: []
body:
  - type: textarea
    id: task
    attributes:
      label: Task
      description: Describe the development task to be completed
    validations:
      required: true
