/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedExercisesExerciseIdRouteImport } from './routes/_authenticated/exercises.$exerciseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExercisesExerciseIdRoute =
  AuthenticatedExercisesExerciseIdRouteImport.update({
    id: '/$exerciseId',
    path: '/$exerciseId',
    getParentRoute: () => AuthenticatedExercisesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/exercises/$exerciseId': typeof AuthenticatedExercisesExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/exercises' | '/' | '/exercises/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/exercises' | '/' | '/exercises/$exerciseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/exercises'
    | '/_authenticated/'
    | '/_authenticated/exercises/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises/$exerciseId': {
      id: '/_authenticated/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AuthenticatedExercisesExerciseIdRouteImport
      parentRoute: typeof AuthenticatedExercisesRoute
    }
  }
}

interface AuthenticatedExercisesRouteChildren {
  AuthenticatedExercisesExerciseIdRoute: typeof AuthenticatedExercisesExerciseIdRoute
}

const AuthenticatedExercisesRouteChildren: AuthenticatedExercisesRouteChildren =
  {
    AuthenticatedExercisesExerciseIdRoute:
      AuthenticatedExercisesExerciseIdRoute,
  }

const AuthenticatedExercisesRouteWithChildren =
  AuthenticatedExercisesRoute._addFileChildren(
    AuthenticatedExercisesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedExercisesRoute: AuthenticatedExercisesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
